GET http://localhost:4000/user-api/users

###
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
  "username": "newuser",
  "password": "password123",
  "age": 25
}

###
GET http://localhost:4000/user-api/users/698030f07521d51f26dc8f17

###
PUT http://localhost:4000/user-api/users/6980559d4ed889acaf8e4940
Content-Type: application/json

{
  "username": "updateduser",
  "password": "newpassword456",
  "age": 26
}

###
DELETE http://localhost:4000/user-api/users/697dbcdd532b4490656914ba


###
POST http://localhost:4000/user-api/auth
Content-Type: application/json

{
  "username":"newuser",
  "password":"password123"
}

###
GET http://localhost:4000/user-api/test

###
GET http://localhost:4000/Product-Api/products

###
POST http://localhost:4000/Product-Api/products
Content-Type: application/json

{
  "productname": "Gaming laptop",
  "price": 75000
}

###
GET http://localhost:4000/Product-Api/products/69802f9c50e527cf858c7895